version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:8000/api
      - REACT_APP_API_VERSION=v1
      - REACT_APP_ENV=development
      - REACT_APP_DEBUG=true
      - REACT_APP_ENABLE_MOCK_API=false
      - REACT_APP_WEBSOCKET_URL=ws://localhost:6001
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - FAST_REFRESH=true
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:3000", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

volumes:
  node_modules:

networks:
  default:
    driver: bridge